import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Dk Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className} suppressHydrationWarning={true}>
        <main>
          <section>
            <Navbar />
            {children}
            <footer className="p-8">
              <h2 className="text-[#5B47C0] text-sm sm:text-base md:sm:text-base lg:text-3xl font-bold text-center">Desarrolado por: <span className="text-white">@nsensedev</span></h2>
            </footer>
          </section>
        </main>
      </body>
    </html>
  );
}
